### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by gep13** [jincod/Cake.Vault#2]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by jincod** [comment]
Added

**Comment by gep13** [comment]
@jincod that is great news! Thank you for taking the time to do that!

Would you also be interested in moving this repository into the Cake-Contrib Organisation on GitHub? You would still have full access rights to the repository in the same way as you do now, it’s just that the repository would live under an organisation. This is part of our, the Cake Teams, attempt to consolidate development effort into one place, to ensure the longevity of the addins that are created for Cake.

Please let me know if you have any questions.

Thanks

**Comment by jincod** [comment]
Sure.

I tried to transfer repo to organization but got error: `You don’t have the permission to create repositories on cake-contrib`

I haven't done it before. What should I do?

**Comment by gep13** [comment]
@jincod again, great news 😄 

The process for transferring a repository into the Organisation is documented here:

https://github.com/cake-contrib/Home#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation

Only the first step needs to be completed by yourself, the rest we would take care of.  Due to the way in which GitHub works, only Organisation Owners can transfer repositories into it.  As a result, the initial transfer of the repository would be made to another individual account, i.e. to my account `gep13` and from there, I would immediately transfer it into the Organisation.

Does that make sense?

**Comment by gep13** [comment]
@jincod Thank you for doing that!  I have done the initial transfer of the repository, I will do the remaining steps later tonight.  Thanks again, I appreciate it!

**Comment by jincod** [comment]
@gep13 thank you for your OSS work!

**Comment by gep13** [comment]
@jincod I have finished setting up this repository with the various permissions etc, so you should now have all the access that you require in order to continue development of this addin.

Please let me know if you have any questions.

**Comment by jincod** [comment]
@gep13 Many thanks !
